physical_env_params:
  network_protocol: enum('NVMe-oF-RDMA', 'NVMe-oF-TCP', 'NVMe-oF-i10')
  disk_type: enum('NVMe')
  memory_resource: int(min=1717986039)
  server_info: map(include('server'), key=ip())
  operator_ip: str()
  operator_work_path: str()
  operator_key_path: str()
  ycsb:
    replicator:
      branch: str()
  rocksdb:
    branch: str()

rubble_params:
  replicator_ip: str()
  replicator_port: int(mint = 1)
  replica_num: int(min = 1)
  shard_num: int(min = 1)
  max_shard_num: int(min = 1)
  shard_info: list(include('shard'))
  thread_num: int(min = 1)
  ycsb_workload: str()
  target_rate: int(min=1)
  cgroup_config:
    memory_limit: str()
    cpuset_cpus: str()
    cpuset_mems: str()
  request_params:
    read_ratio: int(min = 0, max=100)
    update_ratio: int(min = 0, max=100)
    record_count: int(min = 1)
    operation_count: int(min = 1)
  
---
server:
  block_device: include('block_device')
  work_path: str()
  db_path: str()
  remote_device_mnt_path: str()
  user: str()
---
block_device:
  device_path: str()
  nvme_of_namespace: str(required=False)
---
shard:
  tag: str()
  sequence: list(include('rubble_client'))
---
rubble_client:
  ip: ip()
  port: int(min = 1)
