# physical node level config, mostly used at setup time
physical_env_params:
  network_protocol: 'NVMe-oF-RDMA'  # Can be 'NVMe-oF-RDMA', 'NVMe-oF-TCP', 'NVMe-oF-i10'
  # NOTE that server_info list needs to follow the client-target sequence of replication chains.
  # For example, if we have server_info: [A, B, C] as keys, downstream function
  # will establish RDMA conn as such: A->B->C->A,
  # where `->` means a rdma client->target relationship.
  server_info:  # List of servers
    10.10.1.2:
      block_device: 
        # We now only support one block device on each server, 
        #   later this attr should be related to the shard configuration.
        device_path: '/dev/mapper/node--2--vg-sst'
        nvme_of_namespace: 'nvme-target1'
      work_path: '/mnt/code'
      db_path: '/mnt/db'
      remote_device_mnt_path: '/mnt/remote-sst'
      user: 'root'
    10.10.1.3:
      block_device: 
        device_path: '/dev/mapper/node--3--vg-sst'
        nvme_of_namespace: 'nvme-target1'
      work_path: '/mnt/code'
      db_path: '/mnt/db'
      remote_device_mnt_path: '/mnt/remote-sst'
      user: 'root'
    10.10.1.4:
      block_device: 
        device_path: '/dev/mapper/node--4--vg-sst'
        nvme_of_namespace: 'nvme-target1'
      work_path: '/mnt/code'
      db_path: '/mnt/db'
      remote_device_mnt_path: '/mnt/remote-sst'
      user: 'root'
  operator_ip: 10.10.1.1  # IP of the machine where you run the script.
  operator_work_path: '/mnt/code'
  operator_key_path: '/root/.ssh/id_rsa.pub'  # Path to the operator server's public key.
  ycsb:
    branch: single-thread
  rocksdb:
    branch: lhy_dev

# server level config, subject to overwrite in each round of evaluation
rubble_params:
  replicator_ip: '10.10.1.1'
  replicator_port: 50050
  thread_num: 8 # Number of client threads on YCSB
  target_rate: 20000 # Rate to send request by YCSB
  replica_num: 4  # Number of replicas(length of chain).
  shard_num: 2
  max_shard_num: 8
  shard_info:
    - tag: shard-0  # Tag of the shard.
      sequence:
      # IP for the rubble client on each machine, 
      #   following the sequence of chain(head->...->tail).
        - ip: 10.10.1.2
          port: 50051
        - ip: 10.10.1.3
          port: 50101
        - ip: 10.10.1.4
          port: 50101
        - ip: 10.10.1.2
          port: 50052
    - tag: shard-1  # Tag of the shard.
      sequence:
        - ip: 10.10.1.3 
          port: 50051
        - ip: 10.10.1.4
          port: 50102
        - ip: 10.10.1.2
          port: 50102
        - ip: 10.10.1.3
          port: 50052
    - tag: shard-2  # Tag of the shard.
      sequence:
      # IP for the rubble client on each machine, 
      #   following the sequence of chain(head->...->tail).
        - ip: 10.10.1.4 
          port: 50051
        - ip: 10.10.1.2
          port: 50103
        - ip: 10.10.1.3
          port: 50103
        - ip: 10.10.1.4
          port: 50052
    - tag: shard-3  # Tag of the shard.
      sequence:
        - ip: 10.10.1.2 
          port: 50053
        - ip: 10.10.1.3
          port: 50104
        - ip: 10.10.1.4
          port: 50104
        - ip: 10.10.1.2
          port: 50054
  ycsb_workload: a
  cgroup_config:
    memory_limit: 2G
    cpuset_cpus: 0-3
    cpuset_mems: '0'
  request_params:
    record_count: 10000000
    operation_count: 10000000

